### PR TITLE
Fix template parsing

### LINKED ISSUE #17: tmpl.Dockerfile name cannot be changed
I needed to have a separate template file and copied `tmpl.Dockerfile`to `ci.Dockerfile`. Running with different name fails:

```
Version: 0.62 2021-08-22_09:43:34
seihon publish --dry-run=false --template docker/ci.Dockerfile --base-runtime-image alpine:3.13 \
	   --image-name andig/evcc -v "latest" --targets=arm.v6,arm.v8,amd64
Error: template: "tmpl.Dockerfile" is an incomplete or empty template
```

This seems to happen inside `parse.Execute` because `t.Tree` is nil but I couldn't figure out why. The produced architecture dockerfile turns up empty.

### PR DESCRIPTION
**Pull request by andig**
Fix https://github.com/ldez/seihon/issues/17

### CODE REVIEW

**Comment by andig** [comment]
If this fix is correct, I'm wondering if that could be an actual vet check?

**Comment by ldez** [comment]
Fixed by 3f28a201b4402c19d2ad9d898da4fd9a61ccdd4e

**Comment by andig** [comment]
Thank you :) Would you want to release this?

**Comment by ldez** [comment]
It's already done :wink: 

https://github.com/ldez/seihon/releases

**Pull request closed without merging**
